version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn package -DskipTests
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: ~/junit
  trigger-dependents:
    machine: true
    steps:
    - run:
        name: Clone docs
        working_directory: ~/workdir
        command: |
          git clone --depth 1 https://github.com/assadriaz/spring-boot  -examples.git
    - deploy:
        name: Trigger 3rd dependent deployment
        working_directory: ~/workdir/spring-boot-examples
        command: |
          git config credential.helper 'cache --timeout=120'
          git config user.email "<email>"
          git config user.name "CricleCI Bot"
          last_msg=$(git log -1 --pretty=%B)
          git_hash=$(echo $CIRCLE_SHA1 | cut -c1-7)
          echo "git_hash is :"$git_hash
          echo "repo name is :"$CIRCLE_PROJECT_REPONAME
          repo_name_hash=$CIRCLE_PROJECT_REPONAME"("$git_hash")"
          if [[ "$last_msg" == "CCI:"* ]]; then
              git_msg=$($last_msg "->" $repo_name_hash)
          else
              git_msg=$("CCI:"$repo_name_hash)
          fi
          git commit --allow-empty -m "$git_msg"
          # Push quietly to prevent showing the token in log
          git push -q https://${DEMO_GITHUB_TOKEN}@github.com/assadriaz/spring-boot-examples.git master

workflows:
  version: 2
  build_test_deploy:
    jobs:
    - build:
        context: demo
        filters:
          branches:
            only: master
    - trigger-dependents:
        context: demo
        requires:
        - build